// SPDX-License-Identifier: AGPL-3.0-or-later

pub mod linter;

use crate::catalog::linter::{
    ConfigLocation, ConfigPrecedence, LinterId, OwnedToolDef, ToolDef, WalkStop,
};

const CARGO_CONTAINER_ENV: &[(&str, &str)] = &[
    ("CARGO_HOME", "/tmp/.cargo"),
    ("CARGO_TARGET_DIR", "/tmp/target"),
];

static TOOLS: &[ToolDef] = &[
    ToolDef {
        linter_id: LinterId::Python,
        name: "bandit",
        binary_name: "bandit",
        container_image: "bandit",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &[],
        lint_args: Some(include_str!("../../defaults/bandit-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: Some(ConfigPrecedence {
            locations: &[ConfigLocation::Walk {
                filename: ".bandit",
                stop_at: WalkStop::Home,
            }],
            flag: "--configfile",
            cache_filename: "bandit.yaml",
            default: include_str!("../../defaults/bandit.yaml"),
        }),
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Rust,
        name: "cargo-audit",
        binary_name: "cargo",
        container_image: "cargo-audit",
        container_needs_network: true,
        container_needs_rw_mount: true,
        pass_files: false,
        subcommand: &["audit"],
        lint_args: Some(include_str!("../../defaults/cargo-audit-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: None,
        env_vars: &[],
        container_env_vars: CARGO_CONTAINER_ENV,
        probe_args: &["audit", "--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Rust,
        name: "cargo-check-debug",
        binary_name: "cargo",
        container_image: "cargo-check",
        container_needs_network: false,
        container_needs_rw_mount: true,
        pass_files: false,
        subcommand: &["check"],
        lint_args: Some(include_str!("../../defaults/cargo-check-debug-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: None,
        env_vars: &[],
        container_env_vars: CARGO_CONTAINER_ENV,
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Rust,
        name: "cargo-check-release",
        binary_name: "cargo",
        container_image: "cargo-check",
        container_needs_network: false,
        container_needs_rw_mount: true,
        pass_files: false,
        subcommand: &["check"],
        lint_args: Some(include_str!("../../defaults/cargo-check-release-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: None,
        env_vars: &[],
        container_env_vars: CARGO_CONTAINER_ENV,
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Rust,
        name: "cargo-clippy",
        binary_name: "cargo",
        container_image: "cargo-clippy",
        container_needs_network: false,
        container_needs_rw_mount: true,
        pass_files: false,
        subcommand: &["clippy"],
        lint_args: Some(include_str!("../../defaults/cargo-clippy-args")),
        format_print_args: None,
        format_args: Some(include_str!("../../defaults/cargo-clippy-format-args")),
        config_precedence: None,
        env_vars: &[],
        container_env_vars: CARGO_CONTAINER_ENV,
        probe_args: &["clippy", "--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Rust,
        name: "cargo-deny",
        binary_name: "cargo",
        container_image: "cargo-deny",
        container_needs_network: false,
        container_needs_rw_mount: true,
        pass_files: false,
        subcommand: &["deny", "check"],
        lint_args: Some(include_str!("../../defaults/cargo-deny-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: Some(ConfigPrecedence {
            locations: &[
                ConfigLocation::Walk {
                    filename: ".cargo/deny.toml",
                    stop_at: WalkStop::Root,
                },
                ConfigLocation::Walk {
                    filename: "deny.toml",
                    stop_at: WalkStop::Root,
                },
            ],
            flag: "--config",
            cache_filename: "cargo-deny.toml",
            default: include_str!("../../defaults/cargo-deny.toml"),
        }),
        env_vars: &[],
        container_env_vars: CARGO_CONTAINER_ENV,
        probe_args: &["deny", "--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Rust,
        name: "cargo-fmt",
        binary_name: "cargo",
        container_image: "cargo-fmt",
        container_needs_network: false,
        container_needs_rw_mount: true,
        pass_files: false,
        subcommand: &["fmt", "--"],
        lint_args: Some(include_str!("../../defaults/cargo-fmt-args")),
        format_print_args: Some(include_str!("../../defaults/cargo-fmt-format-print-args")),
        format_args: Some(""),
        config_precedence: None,
        env_vars: &[],
        container_env_vars: CARGO_CONTAINER_ENV,
        probe_args: &["fmt", "--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Rust,
        name: "cargo-test",
        binary_name: "cargo",
        container_image: "cargo-test",
        container_needs_network: false,
        container_needs_rw_mount: true,
        pass_files: false,
        subcommand: &["test"],
        lint_args: Some(include_str!("../../defaults/cargo-test-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: None,
        env_vars: &[],
        container_env_vars: CARGO_CONTAINER_ENV,
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Rust,
        name: "cargo-tree",
        binary_name: "cargo",
        container_image: "cargo-tree",
        container_needs_network: false,
        container_needs_rw_mount: true,
        pass_files: false,
        subcommand: &["tree"],
        lint_args: Some(include_str!("../../defaults/cargo-tree-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: None,
        env_vars: &[],
        container_env_vars: CARGO_CONTAINER_ENV,
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Markdown,
        name: "markdownlint-cli2",
        binary_name: "markdownlint-cli2",
        container_image: "markdownlint-cli2",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &[],
        lint_args: None,
        format_print_args: None,
        format_args: Some(include_str!("../../defaults/markdownlint-cli2-format-args")),
        config_precedence: Some(ConfigPrecedence {
            locations: &[
                ConfigLocation::Walk {
                    filename: ".markdownlint-cli2.yaml",
                    stop_at: WalkStop::Root,
                },
                ConfigLocation::Walk {
                    filename: ".markdownlint-cli2.jsonc",
                    stop_at: WalkStop::Root,
                },
            ],
            flag: "--config",
            cache_filename: "markdownlint-cli2.jsonc",
            default: include_str!("../../defaults/markdownlint-cli2.jsonc"),
        }),
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Python,
        name: "mypy",
        binary_name: "mypy",
        container_image: "mypy",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &[],
        lint_args: Some(include_str!("../../defaults/mypy-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: Some(ConfigPrecedence {
            locations: &[ConfigLocation::Walk {
                filename: "mypy.ini",
                stop_at: WalkStop::Home,
            }],
            flag: "--config-file",
            cache_filename: "mypy.ini",
            default: include_str!("../../defaults/mypy.ini"),
        }),
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Python,
        name: "ruff-check",
        binary_name: "ruff",
        container_image: "ruff",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &["check"],
        lint_args: None,
        format_print_args: Some(include_str!("../../defaults/ruff-check-format-print-args")),
        format_args: Some(include_str!("../../defaults/ruff-check-format-args")),
        config_precedence: Some(ConfigPrecedence {
            locations: &[ConfigLocation::Walk {
                filename: "ruff.toml",
                stop_at: WalkStop::Home,
            }],
            flag: "--config",
            cache_filename: "ruff.toml",
            default: include_str!("../../defaults/ruff.toml"),
        }),
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Python,
        name: "ruff-format",
        binary_name: "ruff",
        container_image: "ruff",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &["format"],
        lint_args: Some(include_str!("../../defaults/ruff-format-args")),
        format_print_args: Some(include_str!("../../defaults/ruff-format-format-print-args")),
        format_args: Some(""),
        config_precedence: Some(ConfigPrecedence {
            locations: &[ConfigLocation::Walk {
                filename: "ruff.toml",
                stop_at: WalkStop::Home,
            }],
            flag: "--config",
            cache_filename: "ruff.toml",
            default: include_str!("../../defaults/ruff.toml"),
        }),
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Bash,
        name: "shellcheck",
        binary_name: "shellcheck",
        container_image: "shellcheck",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &[],
        lint_args: Some(include_str!("../../defaults/shellcheck-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: Some(ConfigPrecedence {
            locations: &[
                ConfigLocation::Walk {
                    filename: ".shellcheckrc",
                    stop_at: WalkStop::Root,
                },
                ConfigLocation::Xdg("shellcheck/shellcheckrc"),
                ConfigLocation::Home(".shellcheckrc"),
            ],
            flag: "--rcfile",
            cache_filename: "shellcheckrc",
            default: include_str!("../../defaults/shellcheckrc"),
        }),
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["--version"],
        min_version: Some("0.10.0"),
    },
    ToolDef {
        linter_id: LinterId::Bash,
        name: "shfmt",
        binary_name: "shfmt",
        container_image: "shfmt",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &[],
        lint_args: Some(include_str!("../../defaults/shfmt-lint-args")),
        format_print_args: Some(include_str!("../../defaults/shfmt-format-print-args")),
        format_args: Some(include_str!("../../defaults/shfmt-format-args")),
        config_precedence: None,
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["--version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Go,
        name: "golangci-lint",
        binary_name: "golangci-lint",
        container_image: "golangci-lint",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: false,
        subcommand: &["run"],
        lint_args: Some(include_str!("../../defaults/golangci-lint-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: Some(ConfigPrecedence {
            locations: &[
                ConfigLocation::Walk {
                    filename: ".golangci.yml",
                    stop_at: WalkStop::Root,
                },
                ConfigLocation::Walk {
                    filename: ".golangci.yaml",
                    stop_at: WalkStop::Root,
                },
                ConfigLocation::Walk {
                    filename: ".golangci.toml",
                    stop_at: WalkStop::Root,
                },
                ConfigLocation::Walk {
                    filename: ".golangci.json",
                    stop_at: WalkStop::Root,
                },
            ],
            flag: "--config",
            cache_filename: "golangci-lint.yml",
            default: include_str!("../../defaults/golangci-lint.yml"),
        }),
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["--version"],
        min_version: Some("2.0.0"),
    },
    ToolDef {
        linter_id: LinterId::Go,
        name: "gofumpt",
        binary_name: "gofumpt",
        container_image: "gofumpt",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &[],
        lint_args: Some(include_str!("../../defaults/gofumpt-lint-args")),
        format_print_args: Some(include_str!("../../defaults/gofumpt-format-print-args")),
        format_args: Some(include_str!("../../defaults/gofumpt-format-args")),
        config_precedence: None,
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["-version"],
        min_version: Some("0.6.0"),
    },
    ToolDef {
        linter_id: LinterId::Yaml,
        name: "yamlfmt",
        binary_name: "yamlfmt",
        container_image: "yamlfmt",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &[],
        lint_args: Some(include_str!("../../defaults/yamlfmt-lint-args")),
        format_print_args: Some(include_str!("../../defaults/yamlfmt-format-print-args")),
        format_args: Some(include_str!("../../defaults/yamlfmt-format-args")),
        config_precedence: Some(ConfigPrecedence {
            locations: &[
                ConfigLocation::Walk {
                    filename: ".yamlfmt",
                    stop_at: WalkStop::Home,
                },
                ConfigLocation::Walk {
                    filename: ".yamlfmt.yaml",
                    stop_at: WalkStop::Home,
                },
                ConfigLocation::Walk {
                    filename: ".yamlfmt.yml",
                    stop_at: WalkStop::Home,
                },
            ],
            flag: "-conf",
            cache_filename: "yamlfmt.yaml",
            default: include_str!("../../defaults/yamlfmt.yaml"),
        }),
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["-version"],
        min_version: None,
    },
    ToolDef {
        linter_id: LinterId::Yaml,
        name: "yamllint",
        binary_name: "yamllint",
        container_image: "yamllint",
        container_needs_network: false,
        container_needs_rw_mount: false,
        pass_files: true,
        subcommand: &[],
        lint_args: Some(include_str!("../../defaults/yamllint-args")),
        format_print_args: None,
        format_args: None,
        config_precedence: Some(ConfigPrecedence {
            locations: &[
                ConfigLocation::Walk {
                    filename: ".yamllint",
                    stop_at: WalkStop::Home,
                },
                ConfigLocation::Walk {
                    filename: ".yamllint.yaml",
                    stop_at: WalkStop::Home,
                },
                ConfigLocation::Walk {
                    filename: ".yamllint.yml",
                    stop_at: WalkStop::Home,
                },
                ConfigLocation::EnvVar("YAMLLINT_CONFIG_FILE"),
                ConfigLocation::Xdg("yamllint/config"),
                ConfigLocation::Home(".config/yamllint/config"),
            ],
            flag: "--config-file",
            cache_filename: "yamllint.yaml",
            default: include_str!("../../defaults/yamllint.yaml"),
        }),
        env_vars: &[],
        container_env_vars: &[],
        probe_args: &["--version"],
        min_version: None,
    },
];

#[must_use]
pub fn has_tools_for(id: LinterId) -> bool {
    TOOLS.iter().any(|t| t.linter_id == id)
}

pub fn build_owned_catalog() -> Vec<OwnedToolDef> {
    TOOLS.iter().map(OwnedToolDef::from).collect()
}
